# Generated by Django 5.2.15 on 2026-09-21 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("asa_price", "Asset price"),
                            ("asa_total", "My holding of an asset"),
                            ("total_value", "Portfolio total"),
                            ("total_percent", "Portfolio total, percentage move"),
                        ],
                        max_length=16,
                    ),
                ),
                ("asset_id", models.BigIntegerField(blank=True, null=True)),
                ("address", models.CharField(blank=True, default="", max_length=128)),
                (
                    "direction",
                    models.CharField(
                        choices=[("up", "Rises above"), ("down", "Falls below")],
                        max_length=4,
                    ),
                ),
                ("threshold", models.DecimalField(decimal_places=10, max_digits=30)),
                ("window_seconds", models.PositiveIntegerField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("cooldown_seconds", models.PositiveIntegerField(default=900)),
                (
                    "last_value",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=30, null=True
                    ),
                ),
                ("last_fired_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["asset_id", "active"], name="alert_asset_active_idx"
                    ),
                    models.Index(
                        fields=["address", "active"], name="alert_address_active_idx"
                    ),
                    models.Index(fields=["user", "active"], name="alert_user_active_idx"),
                ],
            },
        ),
    ]
