# Generated by Django 5.2.15 on 2026-09-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("widgets", "0002_pushsubscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alertrule",
            name="subject",
            field=models.CharField(
                choices=[
                    ("asa_price", "Asset price"),
                    ("asa_price_percent", "Asset price, percentage move"),
                    ("asa_total", "My holding of an asset"),
                    ("total_value", "Portfolio total"),
                    ("total_percent", "Portfolio total, percentage move"),
                ],
                max_length=32,
            ),
        ),
    ]
