# Generated by Django 5.2.15 on 2026-09-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("widgets", "0003_alter_alertrule_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertrule",
            name="asset_unit",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="alertrule",
            name="threshold_unit",
            field=models.CharField(default="algo", max_length=4),
        ),
        migrations.AlterField(
            model_name="alertrule",
            name="subject",
            field=models.CharField(
                choices=[
                    ("asa_price", "Asset price"),
                    ("asa_price_percent", "Asset price, percentage move"),
                    ("asa_amount", "How much of an asset I hold"),
                    ("asa_total", "What my holding of an asset is worth"),
                    ("total_value", "Portfolio total"),
                    ("total_percent", "Portfolio total, percentage move"),
                ],
                max_length=32,
            ),
        ),
    ]
